#- hosts: all
#  become: true
#  become_user: root
#  gather_facts: false
#  tasks:
#    - name: Add new user to install composer
#      ansible.builtin.user:
#        name: not_root
#        comment: I am not the root user
#        group: www-data

#- hosts: all
#  become: true
#  become_user: not_root
#  gather_facts: false
#  tasks:
#    - name: Creating Project with Composer
#      community.general.composer:
#        command: create-project
#        working_dir: /var/www/classiq04
#        prefer_dist: true

#    - name: Create Project
#      shell:  cd /var/www/classiq04/ && composer create-project && cd
