- name: Upgrade System
  apt: upgrade=dist update_cache=yes

- name: Installing snapd
  apt:
    name: snapd

- name: Installing Core
  community.general.snap:
    name: core

- name: Refreshing Core
  command: snap refresh core

- name: Installing certbot
  community.general.snap:
    name: certbot
    classic: true

- name: Configuring certbot
  shell: sudo ln -s /snap/bin/certbot /usr/bin/certbot

- name: Requesting SSL Certificate
  shell: sudo certbot --apache --agree-tos --redirect -m classicsam04@gmail.com -d classiq04.com -d www.classiq04.com

- name: Copy htaccess new file to ensure mod rewrite
  ansible.builtin.copy:
    src: /home/ubuntu/exam/files/.htaccess2
    dest: /var/www/classiq04/.htaccess
    remote_src: no

  notify:
    - restart apache2

